In [1]:
import yfinance as yf
import pandas as pd
import datetime as dt
import time
from datetime import timedelta
import pandas_ta as ta

from sklearn.metrics import precision_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
def get_data(year,month,day):
    start = dt.datetime(1999,1,1)
    end = dt.datetime.now()
    ticker = 'SPY'  

    df = yf.download(ticker,start,end)
    
    return df

In [3]:
df = get_data(1999,1,1)

[*********************100%***********************]  1 of 1 completed

In [4]:
df

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1999-01-04,123.375000,125.218750,121.718750,123.031250,79.169907,9450400
1999-01-05,122.937500,124.875000,122.937500,124.437500,80.074829,8031000
1999-01-06,125.812500,127.750000,125.750000,127.437500,82.005302,7737700
1999-01-07,126.375000,127.218750,125.781250,126.812500,81.603127,5504900
1999-01-08,128.187500,128.500000,125.968750,127.750000,82.206390,6224400
...,...,...,...,...,...,...
2023-08-18,433.369995,437.570007,433.010010,436.500000,436.500000,98758400
2023-08-21,437.549988,440.109985,435.320007,439.339996,439.339996,68719000
2023-08-22,441.179993,441.179993,437.570007,438.149994,438.149994,65062900
2023-08-23,439.250000,443.670013,439.100006,443.029999,443.029999,68441000
2023-08-24,444.690002,445.220001,436.859985,436.890015,436.890015,88379900

In [5]:
# add features to model
df['Range'] = abs(df['High']-df['Low'])
df['RSI 14'] = ta.rsi(df['Close'], 14)
df['SMA 20'] = ta.sma(df['Close'], 20)
df['SMA 50'] = ta.sma(df['Close'], 50)
df['SMA 200'] = ta.sma(df['Close'], 200)
df['EMA 12'] = ta.ema(df['Close'], 12)
df['EMA 26'] = ta.ema(df['Close'], 26)
df['ATR'] = ta.atr(df['High'], df['Low'], df['Close'] )

# create 'Tomorrow' column
# it's the 'Close' value from the previous day
# will be used to create a target
df['Tomorrow'] = df['Close'].shift(-1)
df['Target'] = (df['Tomorrow'] > df['Close']).astype(int)
df = df.loc['2000-01-01':]
df.drop('Adj Close', axis=1, inplace=True)
df.drop(df.tail(1).index, inplace=True)

C:\Users\13148\AppData\Local\Temp\ipykernel_684\3650632616.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Adj Close', axis=1, inplace=True)
C:\Users\13148\AppData\Local\Temp\ipykernel_684\3650632616.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(df.tail(1).index, inplace=True)

In [6]:
df

,Open,High,Low,Close,Volume,Range,RSI 14,SMA 20,SMA 50,SMA 200,EMA 12,EMA 26,ATR,Tomorrow,Target
Date,,,,,,,,,,,,,,,
2000-01-03,148.250000,148.250000,143.875000,145.437500,8164300,4.375000,60.123229,143.598437,140.252500,134.929844,145.100225,143.284849,1.978058,139.750000,0
2000-01-04,143.531250,144.062500,139.640625,139.750000,8089800,4.421875,39.912317,143.446875,140.445625,134.978906,144.277113,143.023008,2.250830,140.000000,1
2000-01-05,139.937500,141.531250,137.250000,140.000000,12177900,4.281250,40.853504,143.365625,140.656875,135.047969,143.619096,142.799082,2.395860,137.750000,0
2000-01-06,139.625000,141.500000,137.750000,137.750000,6227200,3.750000,35.468775,143.217187,140.855625,135.102188,142.716158,142.425076,2.492585,145.750000,1
2000-01-07,140.312500,145.750000,140.062500,145.750000,8066500,5.687500,57.113342,143.434375,141.168125,135.183437,143.182903,142.671366,2.885971,146.250000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-17,441.160004,441.429993,435.750000,436.290009,95711300,5.679993,34.859752,449.524503,443.950400,411.748550,445.039914,446.091766,4.516194,436.500000,1
2023-08-18,433.369995,437.570007,433.010010,436.500000,98758400,4.559998,35.283750,448.740503,444.149401,412.000000,443.726081,445.381265,4.519322,439.339996,1
2023-08-21,437.549988,440.109985,435.320007,439.339996,68719000,4.789978,40.887683,447.997502,444.353600,412.274100,443.051299,444.933763,4.538655,438.149994,0
2023-08-22,441.179993,441.179993,437.570007,438.149994,65062900,3.609985,39.350095,447.133002,444.518600,412.590500,442.297252,444.431262,4.472321,443.029999,1
2023-08-23,439.250000,443.670013,439.100006,443.029999,68441000,4.570007,47.987997,446.509001,444.703201,412.950600,442.409982,444.327464,4.547157,436.890015,0

In [7]:
# loop through dataframe and add all features to a list
# removes 'Tomorrow' and 'Target' column from the list 
def get_features(dataframe):
    features = []
    for column in dataframe:
        features.append(column)
    
    features.pop(-1)
    features.pop(-1)
    
    return features

In [8]:
features = get_features(df)

In [9]:
def fit_train_score(dataframe, n_est, min_split):    
    # n_estimators = number of decision trees
    # min_samples_split = higher it is set, the less accurtate it is, the less it will overfit
    model = RandomForestClassifier(n_estimators=n_est, min_samples_split=min_split, random_state=1)

    train = df.iloc[:-100]
    test = df.iloc[-100:]

    # fit and train model
    model.fit(train[features], train['Target'])
    predictions = model.predict(test[features])
    #predictions_series = pd.Series(predictions, index=test.index)

    # precision of training data
    predictions_training = model.predict(train[features])
    #print("Precision of training data")
    #print(precision_score(train['Target'], predictions_training))
    #print("")
    
    # precision of testing data
    #print("Precision of testing data:")
    #print(precision_score(test['Target'], predictions))
    #print("")
    
    # print classification report for testing data
    #print("Classification Report")
    #print(classification_report(test['Target'], predictions))
    #print("")
    
    test_dict = {
        'n_estimators':n_est,
        'min_samples_split':min_split,
        'training precision':precision_score(train['Target'], predictions_training),
        'testing precision':precision_score(test['Target'], predictions)
                }
    
    return test_dict

In [10]:
fit_train_score(df,200,750)

{'n_estimators': 200,
 'min_samples_split': 750,
 'training precision': 0.5771648752788481,
 'testing precision': 0.5408163265306123}

In [11]:
fit_train_score(df,300,400)

{'n_estimators': 300,
 'min_samples_split': 400,
 'training precision': 0.6042380136986302,
 'testing precision': 0.5353535353535354}

In [17]:
# loop through possible n_estimator values and min_sample_split values
start_time = time.time()

test_list = []
for n in range(200,301,50):

    for m in range(500,801,50):

        result_dict = fit_train_score(df,n,m)
        test_list.append(result_dict)
        print("--- %s minutes ---" % ((time.time() - start_time)/60))
        print(result_dict)
        print("")

results_df = pd.DataFrame(test_list)
print("--- %s minutes ---" % ((time.time() - start_time)/60))

--- 0.2163983702659607 minutes ---
{'n_estimators': 200, 'min_samples_split': 500, 'training precision': 0.5914494264859228, 'testing precision': 0.5408163265306123}

--- 0.42201440731684364 minutes ---
{'n_estimators': 200, 'min_samples_split': 550, 'training precision': 0.5873806558738066, 'testing precision': 0.5306122448979592}

--- 0.6243352929751078 minutes ---
{'n_estimators': 200, 'min_samples_split': 600, 'training precision': 0.5851195383347073, 'testing precision': 0.5306122448979592}

--- 0.8213376641273499 minutes ---
{'n_estimators': 200, 'min_samples_split': 650, 'training precision': 0.583607230895645, 'testing precision': 0.5353535353535354}

--- 1.020215348402659 minutes ---
{'n_estimators': 200, 'min_samples_split': 700, 'training precision': 0.5806781045751634, 'testing precision': 0.5306122448979592}

--- 1.2249446352322897 minutes ---
{'n_estimators': 200, 'min_samples_split': 750, 'training precision': 0.5771648752788481, 'testing precision': 0.5408163265306123}

--- 1.410197925567627 minutes ---
{'n_estimators': 200, 'min_samples_split': 800, 'training precision': 0.5752016129032258, 'testing precision': 0.5306122448979592}

--- 1.678734334309896 minutes ---
{'n_estimators': 250, 'min_samples_split': 500, 'training precision': 0.5906724963564439, 'testing precision': 0.5454545454545454}

--- 1.947630019982656 minutes ---
{'n_estimators': 250, 'min_samples_split': 550, 'training precision': 0.5872719734660033, 'testing precision': 0.5306122448979592}

--- 2.208464733759562 minutes ---
{'n_estimators': 250, 'min_samples_split': 600, 'training precision': 0.5850648014811767, 'testing precision': 0.5306122448979592}

--- 2.4656121651331584 minutes ---
{'n_estimators': 250, 'min_samples_split': 650, 'training precision': 0.5824108241082411, 'testing precision': 0.5353535353535354}

--- 2.715496265888214 minutes ---
{'n_estimators': 250, 'min_samples_split': 700, 'training precision': 0.5796334012219959, 'testing precision': 0.5306122448979592}

--- 2.960649593671163 minutes ---
{'n_estimators': 250, 'min_samples_split': 750, 'training precision': 0.5767441860465117, 'testing precision': 0.5353535353535354}

--- 3.2147517999013266 minutes ---
{'n_estimators': 250, 'min_samples_split': 800, 'training precision': 0.574070351758794, 'testing precision': 0.5306122448979592}

--- 3.542418913046519 minutes ---
{'n_estimators': 300, 'min_samples_split': 500, 'training precision': 0.58889816360601, 'testing precision': 0.5454545454545454}

--- 3.8564050952593485 minutes ---
{'n_estimators': 300, 'min_samples_split': 550, 'training precision': 0.5863928645509231, 'testing precision': 0.5353535353535354}

--- 4.177126578489939 minutes ---
{'n_estimators': 300, 'min_samples_split': 600, 'training precision': 0.583934088568486, 'testing precision': 0.5353535353535354}

--- 4.521711389223735 minutes ---
{'n_estimators': 300, 'min_samples_split': 650, 'training precision': 0.5818293683347006, 'testing precision': 0.54}

--- 4.82542165517807 minutes ---
{'n_estimators': 300, 'min_samples_split': 700, 'training precision': 0.5801713586291309, 'testing precision': 0.5353535353535354}

--- 5.133457545439402 minutes ---
{'n_estimators': 300, 'min_samples_split': 750, 'training precision': 0.5766970618034448, 'testing precision': 0.5353535353535354}

--- 5.42138481537501 minutes ---
{'n_estimators': 300, 'min_samples_split': 800, 'training precision': 0.5747381144238517, 'testing precision': 0.5353535353535354}

--- 5.421401762962342 minutes ---

In [18]:
results_df['testing delta'] = abs(results_df['testing precision'] - results_df['training precision'])*100
results_df_precision_sorted = results_df.copy().sort_values(by='testing precision', ascending=False)